"""create initial tables

Revision ID: 001
Revises:
Create Date: 2026-03-09

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(255),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(255),
            nullable=False,
        ),
        sa.Column(
            "clerk_id",
            sa.String(255),
            nullable=True,
        ),
        sa.Column(
            "role",
            sa.String(50),
            server_default="creator",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("clerk_id"),
    )

    op.create_table(
        "projects",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(255),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(50),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "game_profiles",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "genre",
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            "target_audience",
            sa.String(255),
            nullable=True,
        ),
        sa.Column(
            "core_mechanics",
            postgresql.JSONB(),
            nullable=True,
        ),
        sa.Column(
            "art_style",
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            "brand_guidelines",
            postgresql.JSONB(),
            nullable=True,
        ),
        sa.Column(
            "competitors",
            postgresql.JSONB(),
            nullable=True,
        ),
        sa.Column(
            "key_selling_points",
            postgresql.JSONB(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"]
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )

    op.create_table(
        "assets",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "asset_type",
            sa.String(50),
            nullable=False,
        ),
        sa.Column(
            "s3_key",
            sa.String(500),
            nullable=False,
        ),
        sa.Column(
            "filename",
            sa.String(255),
            nullable=False,
        ),
        sa.Column(
            "content_type",
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            "size_bytes",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "duration_ms",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "width",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "height",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"]
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_assets_project_id",
        "assets",
        ["project_id"],
    )

    op.create_table(
        "creative_briefs",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "hook_type",
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            "narrative_angle",
            sa.String(255),
            nullable=True,
        ),
        sa.Column("script", sa.Text(), nullable=True),
        sa.Column(
            "voiceover_text", sa.Text(), nullable=True
        ),
        sa.Column(
            "target_emotion",
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            "cta_text",
            sa.String(255),
            nullable=True,
        ),
        sa.Column(
            "reference_ads",
            postgresql.JSONB(),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "target_format",
            sa.String(20),
            server_default="9:16",
            nullable=False,
        ),
        sa.Column(
            "target_duration",
            sa.Integer(),
            server_default="15",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(50),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "generated_by",
            sa.String(50),
            server_default="agent",
            nullable=False,
        ),
        sa.Column(
            "scene_plan",
            postgresql.JSONB(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"]
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_creative_briefs_project_id",
        "creative_briefs",
        ["project_id"],
    )

    op.create_table(
        "render_jobs",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "brief_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(50),
            server_default="queued",
            nullable=False,
        ),
        sa.Column(
            "composition",
            postgresql.JSONB(),
            nullable=True,
        ),
        sa.Column(
            "output_s3_key",
            sa.String(500),
            nullable=True,
        ),
        sa.Column(
            "render_duration_ms",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "error_message", sa.Text(), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["brief_id"], ["creative_briefs.id"]
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_render_jobs_brief_id",
        "render_jobs",
        ["brief_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_render_jobs_brief_id")
    op.drop_table("render_jobs")
    op.drop_index("ix_creative_briefs_project_id")
    op.drop_table("creative_briefs")
    op.drop_index("ix_assets_project_id")
    op.drop_table("assets")
    op.drop_table("game_profiles")
    op.drop_table("projects")
    op.drop_table("users")
